//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Reposistory
{
    using System;
    using System.Collections.Generic;
    
    public partial class logindetl
    {
        public long SlNo { get; set; }
        public int userlogid { get; set; }
        public Nullable<System.DateTime> logindt { get; set; }
        public string ipaddress { get; set; }
        public string computername { get; set; }
        public string logtime { get; set; }
        public string macaddress { get; set; }
        public string GeoLocation { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string OSFamily { get; set; }
        public string OSVersion { get; set; }
        public string BrowserFamily { get; set; }
        public string BrowserVersion { get; set; }
        public string DeviceFamily { get; set; }
        public string DeviceFormFactor { get; set; }
        public string devBrand { get; set; }
        public string devModel { get; set; }
        public Nullable<bool> devbot { get; set; }
        public Nullable<int> LocationType { get; set; }
        public string LocationResponse { get; set; }
    }
}
