//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Reposistory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoldmedalTicketEntities : DbContext
    {
        public GoldmedalTicketEntities()
            : base("name=GoldmedalTicketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryMaster> CategoryMasters { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<MenuCategoryMaster> MenuCategoryMasters { get; set; }
        public virtual DbSet<MenuMaster> MenuMasters { get; set; }
        public virtual DbSet<SubMenuMaster> SubMenuMasters { get; set; }
        public virtual DbSet<AgentCategoryAssigned> AgentCategoryAssigneds { get; set; }
        public virtual DbSet<AgentCheckInStatusDetail> AgentCheckInStatusDetails { get; set; }
        public virtual DbSet<AgentCheckInStatusSummary> AgentCheckInStatusSummaries { get; set; }
        public virtual DbSet<AttachmentDetail> AttachmentDetails { get; set; }
        public virtual DbSet<OverdueType> OverdueTypes { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<ProfileImage> ProfileImages { get; set; }
        public virtual DbSet<ProfileImageStatu> ProfileImageStatus { get; set; }
        public virtual DbSet<RegisterVerification> RegisterVerifications { get; set; }
        public virtual DbSet<ReplyAttachment> ReplyAttachments { get; set; }
        public virtual DbSet<ReplyAttachmentDetail> ReplyAttachmentDetails { get; set; }
        public virtual DbSet<ResetPasswordVerification> ResetPasswordVerifications { get; set; }
        public virtual DbSet<SavedAssignedRole> SavedAssignedRoles { get; set; }
        public virtual DbSet<Signature> Signatures { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TicketDeleteLockStatu> TicketDeleteLockStatus { get; set; }
        public virtual DbSet<TicketDetail> TicketDetails { get; set; }
        public virtual DbSet<TicketEscalationHistory> TicketEscalationHistories { get; set; }
        public virtual DbSet<TicketHistory> TicketHistories { get; set; }
        public virtual DbSet<TicketReply> TicketReplies { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketStatu> TicketStatus { get; set; }
        public virtual DbSet<UserToken> UserTokens { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<PasswordMaster> PasswordMasters { get; set; }
        public virtual DbSet<Usermaster> Usermasters { get; set; }
        public virtual DbSet<CategoryConfigration> CategoryConfigrations { get; set; }
        public virtual DbSet<Login_history> Login_history { get; set; }
        public virtual DbSet<logindetl> logindetls { get; set; }
        public virtual DbSet<BusinessHour> BusinessHours { get; set; }
    }
}
