//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Reposistory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long SLNO { get; set; }
        public string TrackingId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<long> PriorityId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string Contact { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<bool> StatusAssigned { get; set; }
        public Nullable<long> InternalUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreateId { get; set; }
        public Nullable<System.DateTime> Createdt { get; set; }
        public Nullable<long> ModifyId { get; set; }
        public Nullable<System.DateTime> Modifydt { get; set; }
        public Nullable<long> DelId { get; set; }
        public Nullable<System.DateTime> Deldt { get; set; }
        public Nullable<long> LogNo { get; set; }
    }
}
